import './globals.css'
import type { Metadata } from 'next'
import "@radix-ui/themes/styles.css";
import"./default_font.css"
import { Container, Theme } from "@radix-ui/themes";
import { Inter } from 'next/font/google'
import NavBar from './NavBar';
import AuthProvider from './auth/Provider';
import QueryClientProvider from './QueryClientProvider'; // ← import our wrapper
const inter = Inter({ subsets: ['latin'] ,variable: "--font-inter", })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>

        {/* AuthProvider — handles Google session, makes useSession() available everywhere */}
        <AuthProvider>

          {/* QueryClientProvider — makes useQuery() available everywhere  */}
          {/* must wrap the entire app so any component can use TanStack Query */}
          {/* AssigneeSelect uses useQuery() — it needs this provider above it in the tree */}
          <QueryClientProvider>

            <Theme appearance="light" accentColor="ruby" radius="large">
              <div className="min-h-screen flex flex-col">
                <NavBar />
                <main className="p-6 flex-grow">
                  <Container>{children}</Container>
                </main>
              </div>
            </Theme>

          </QueryClientProvider>

        </AuthProvider>
      </body>
    </html>
  )
}